version: '3.8'

services:
  galaxy_drive:
    build: .
    image: aleksandrkamen/galaxy_drive
    restart: always
    depends_on:
      - postgres_db
      - redis
      - minio
    ports:
      - '8080:8080'
    environment:
      SPRING_PROFILES_ACTIVE: "prod"
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_BUCKET: ${MINIO_BUCKET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URI}
      GIT_HUB_CLIENT_ID: ${GIT_HUB_CLIENT_ID}
      GIT_HUB_CLIENT_SECRET: ${GIT_HUB_CLIENT_SECRET}
      GIT_HUB_REDIRECT_URI: ${GIT_HUB_REDIRECT_URI}

  postgres_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis
    restart: always
    volumes:
      - redis_data:/data

  minio:
    image: minio/minio
    restart: always
    command: server /data --console-address ":${MINIO_CONSOLE_PORT}"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - '9000:9000'
      - ${MINIO_CONSOLE_PORT}:${MINIO_CONSOLE_PORT}
    volumes:
      - minio_data:/data

  adminer:
    image: adminer
    restart: always
    ports:
      - ${ADMINER_PORT}

volumes:
  postgres_data:
  redis_data:
  minio_data:
