spring:
  datasource:
    url: jdbc:postgresql://postgres_db:5432/users
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
  session:
    store-type: redis
    timeout: 3600
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI}
          github:
            client-id: ${GIT_HUB_CLIENT_ID}
            client-secret: ${GIT_HUB_CLIENT_SECRET}
            redirect-uri: ${GIT_HUB_REDIRECT_URI}
            scope:
              - user:email
              - read:user

  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  data:
    redis:
      host: redis
minio:
  url: http://minio:9000
  bucket: user-files
  accessKey: minio_user_dev
  secretKey: minio_password_dev
  memoryLimit: 1073741824








