spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://${HOST}:5434/${POSTGRES_DATABASE}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false

  session:
    store-type: redis
    timeout: 1800

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI}

          github:
            client-id: ${GIT_HUB_CLIENT_ID}
            client-secret: ${GIT_HUB_CLIENT_SECRET}
            redirect-uri: ${GIT_HUB_REDIRECT_URI}
            scope:
              - user:email
              - read:user




